### ISSUE TITLE
as_dict() and from_dict() additions to MatMethods input sets

### ISSUE THREAD

**Issue by computron** [hackingmaterials/MatMethods#18]
@matk86 

Are explicit versions of these methods really necessary? They are kind of cumbersome to maintain and I figure that superclass DictVaspInputSet could just take care of dict-ifying everything. Let me know if it's not the case.

**Comment by matk86** [comment]
i think they are needed because the inputsets that subclass DictInputSet also add 'config_dict_override'(apart from some other extra params) as an extra initialization parameter that is used to to override the default parameters set from the yaml file in the initializer. During the tests i noticed that the setting overridden via config_dict_override disappeared during the serailization/deserialization steps of fireworks. If the paramters are not overridden then the default as_dict and from_dict are fine.

**Comment by computron** [comment]
Hmm ok ... I am closing for now but will try to think about it more after the grand unification of input sets with pymatgen
