### ISSUE TITLE
How to reference calc_dir of non parent run?

### ISSUE THREAD

**Issue by blondegeek** [hackingmaterials/MatMethods#22]
Suppose I have a workflow in which the job dependency DAG and the copying of previous output DAG are not the same. Here’s an example workflow:

fireworks:
- fw: classA # 0th firework
- fw: classB # 1st firework
   params:
       parents: 0
- fw: classC # 2nd firework
  params:
       parents: 1
       grab_output_from: 0

The 2nd firework will not run until the 1st is complete, but I would like the 2nd firework to run a continuation job from the output files of the 0th firework. What is the best way for the 2nd firework to get the calculation directory of the 0th firework? Can this be specified in the YAML file?

Thanks!

**Comment by computron** [comment]
Hi Tess,

There are several answers to this question, hopefully something useful is embedded in here:

* First let me say that the YAML format you're talking about is just a test YAML format being used in MatMethods. It is not the FireWorks YAML format. What that means is that there is room to change the format if necessary. It also means that I don't use this format myself much (yet)

* If ClassC needs the outputs from 0, you might consider adding 0 as a parent. I know it is implied if 0->1 and 1->2 that 0->2 ... anyway this is just minor. For now just know that "parents" is a list and you can have more than one parent if you want.

* As for getting output files from "2 jobs up" in the chain - you should review the docs of PassCalcLocs and CopyVaspOutputs. Those two FireTasks work together in order to (i) pass the information of where the previous jobs are located and (ii) grab the job from those previous locations (respectively). The CopyVaspOutputs by default just gives you "one job up". But if you set that to a "name" you can get the outputs of the PassCalcLocs with that "name". Meaning, you should be able to get the outputs from any job up in the chain.

There are two complications:
(i) I have noticed that PassCalcLocs is not really doing its job in terms of maintaining the directories of all the previous runs when passing info. If true then this is a bug that will directly affect your ability to do what you want to do. Just hold tight for now, I will fix it as soon as I get out of proposal land

(ii) You will need to be able to set PassCalcLocs and CopyVaspOutputs parameters from the YAML file, if you are constructing the job from a YAML file. I don't think this is currently possible unless you also change the kwargs of the FWS themselves. What I would suggest is to ditch the YAML format unless you are doing something really simple. Otherwise, construct the workflows using Python - by chaining together FireTasks into Fireworks and Fireworks into Workflows. You should be able to reuse existing FireTasks w/o modification, and be able to refer to existing Fireworks with minimal mods.

**Comment by blondegeek** [comment]
Hi Anubhav,

Thanks for the reply. I'll give the CopyVaspOutputs calc_loc = firework_name option a try and let you know if I see anything funny.

**Comment by computron** [comment]
FYI there was indeed a bug in PassCalcLoc, fixed via 38d39f986f05b502cbf8938c442c0259364fc952

I am closing for now
