### ISSUE TITLE
Drone suggestions

### ISSUE THREAD

**Issue by shyuep** [hackingmaterials/MatMethods#6]
## System

* Version: Master

## Summary

* MMVaspToDbTaskDrone is written in a rather inflexible manner. For example, there is a calculation_initial and calculation key in assimilate. When happens if the run is only a single run? It is replicated?

## Suggested solution

* I think basically calculations should be a dict or a list. Originally, it was a list but that made it difficult to handle. But we can always have a dict with keyword: vasprun. E.g., {"relax1": <vasprun>, "relax2": <vasprun>}.
* I would suggest revising some key names. For example, unit_cell_formula and pretty_formula suggests they are the same type, when in fact the former is a dict and the latter is a string. I suggest we rename all the dict versions as composition. E.g., unit_cell_composition and reduced_composition. Drop the word "cell" from reduced_composition since after reduction, the concept of a "cell" doesn't make sense.
* Do we want to invert the names? E.g., composition_reduced, composition_unit_cell instead of "reduced_composition" and "unit_cell_composition".
* I would drop the word "final" from "final_energy" and "final_energy_per_atom" for brevity.

**Comment by shyuep** [comment]
Just a note that I can do these changes myself if needed. I am posting first for discussion before I do something that break stuff.

**Comment by computron** [comment]
>> MMVaspToDbTaskDrone is written in a rather inflexible manner. For
example, there is a calculation_initial and calculation key in assimilate.
When happens if the run is only a single run? It is replicated?

I will let Kiran answer in more detail, but I believe the motivation (at
least from my point of view) is the following:
- 99% of the time, I want to query the "final" version of a calculation. in
the language of the original drone, query on a field like
calculations[-1][output][efermi].
- But Mongo doesn't allow the -1 indexing of arrays like Python (
http://stackoverflow.com/questions/28680295/mongodb-query-on-the-last-element-of-an-array).
This makes it very difficult to simply just get the "final" information in
detail without moving it over to the output key which is a dedicated area
for "VIPs" - very important properties.

The proposed new situation is:
calculation - the "final" calculation
calculations_initial - None if there is only 1 calculation. An array of
calcs if there are other things.

i.e., most calcs will have None for calculations_initial. But a VASP double
relaxation will have the final run in "calculation", and the initial
relaxation as a 1-element array in calculations_initial. A k-point
convergence would have the last run in the "calculation", and everything
else in calculations_initial.

The good thing is that it makes it easy to get what I want (again, the
final calculation is what I care about 99% of the time, and so I can focus
my attention on that single key). The bad thing is that it splits up the
calcs into two keys in the cases where I want to see what happens for
example in the course of a k-point run. But this latter case never happens
in practice and I wouldn't mind concatenating in those cases. There is no
replication.

If there is a better solution that addresses these concerns I'd certainly
be open to it.

>> I think basically calculations should be a dict or a list. Originally,
it was a list but that made it difficult to handle. But we can always have
a dict with keyword: vasprun. E.g., {"relax1": , "relax2": }.

Again, for me the main use case is to be able to easily query just the last
calculation via MongoDB. e.g., regardless of calculation type, find all
documents where the last calculation has some property (e.g., INCAR tag
shows spin orbit coupling on). If some of the documents are "relax2" and
others aren't, such searches are difficult.

>> I would suggest revising some key names. For example, unit_cell_formula
and pretty_formula suggests they are the same type, when in fact the former
is a dict and the latter is a string. I suggest we rename all the dict
versions as composition. E.g., unit_cell_composition and
reduced_composition. Drop the word "cell" from reduced_composition since
after reduction, the concept of a "cell" doesn't make sense.

Agree

>> Do we want to invert the names? E.g., composition_reduced,
composition_unit_cell instead of "reduced_composition" and
"unit_cell_composition".

Agree, I prefer inversion (I always liked the noun-adjective order in
Spanish better than English). The only thing is whether the mapping to
pymatgen names is then destroyed.

>> I would drop the word "final" from "final_energy" and
"final_energy_per_atom" for brevity.

Agree

Best,
Anubhav

**Comment by computron** [comment]
Thanks for implementing the changes. For the calculations key, let's go with your suggestion, but rename the key to "calculations_reversed". Will you be willing to implement?

Here are my thoughts on the subject:

1. I would like to rename to "calculations_reversed" (even though it is a mouthful) for two reasons. First, as a new user, I would not expect the reverse order, and it would be difficult to figure it out unless I read documentation very carefully. There is a high likelihood of new users assuming it is sorted in oldest->newest order. Second, existing users of pymatgen/drones/etc. should be given some alert that this key is different than the old calculations key. There is a very high likelihood of mistakes if we kept the same name, since code that referenced the old model would still work (not break since it is the same type of data structure and same key name) on the new key but give wrong results. Basically, principle of least surprise is very important to me.

2. The solution of "calculations_initial" and "calcaultion_final" had one neat feature in that it would be easy to query on both the first and last calculation. e.g., calculations_initial.0.input.incar vs. calculation_final.input.incar. The new strategy makes it more difficult to query on the first calc. But, I think the gain in simplification and not needing to know that there are two dict keys pertaining to calculations, with different format (list of dict vs dict) is worth going with your solution.

**Comment by shyuep** [comment]
Ok. Let's reduce the name to calcs_reversed.
